export const ACTION_TYPE = {
    ADD_NOTES: 'ADD_NOTES',
    UPDATE_NOTES: 'UPDATE_NOTES',
    DELETE_NOTES: 'DELETE_NOTES',
    NOTES_FOR_UPDATE: 'NOTES_FOR_UPDATE',
    APPLY_FILTER: 'APPLY_FILTER',

}